name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t prasad729/polaroid-app:latest .
          docker push prasad729/polaroid-app:latest
          
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull prasad729/polaroid-app:latest
      - name: Delete old container
        run: docker rm -f prasad729/polaroid-app:latest
      - name: Run Docker Container
        run: docker run -d -p 3500:3500 --name web-server-1 prasad729/polaroid-app:latest